<?php

namespace Database\Seeders;

use App\Enums\FuelType;
use App\Models\Car;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'id' => 1,
                'make' => 'Audi',
                'model' => 'A4',
                'year' => 2021,
                'license_plate' => 'AA-1001',
                'price_per_day' => 75.00,
                'mileage' => 28000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Berline de luxe avec des fonctionnalités haut de gamme et une conduite fluide.',
            ],
            [
                'id' => 2,
                'make' => 'Audi',
                'model' => 'Q5',
                'year' => 2020,
                'license_plate' => 'AA-1002',
                'price_per_day' => 85.00,
                'mileage' => 35000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'SUV compact de luxe avec transmission intégrale et intérieur spacieux.',
            ],
            [
                'id' => 3,
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2022,
                'license_plate' => 'BB-2003',
                'price_per_day' => 120.00,
                'mileage' => 15000,
                'transmission' => 'automatic',
                'seats' => 7,
                'description' => 'SUV haut de gamme avec technologies avancées et performances exceptionnelles.',
            ],
            [
                'id' => 4,
                'make' => 'Chevrolet',
                'model' => 'Camaro',
                'year' => 2021,
                'license_plate' => 'CC-3004',
                'price_per_day' => 95.00,
                'mileage' => 22000,
                'transmission' => 'manual',
                'seats' => 4,
                'description' => 'Voiture de sport puissante avec un style agressif et des performances exaltantes.',
            ],
            [
                'id' => 5,
                'make' => 'Chevrolet',
                'model' => 'Malibu',
                'year' => 2020,
                'license_plate' => 'CC-3005',
                'price_per_day' => 55.00,
                'mileage' => 42000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Berline de taille moyenne offrant confort et efficacité énergétique.',
            ],
            [
                'id' => 6,
                'make' => 'Chevrolet',
                'model' => 'Tahoe',
                'year' => 2021,
                'license_plate' => 'CC-3006',
                'price_per_day' => 110.00,
                'mileage' => 31000,
                'transmission' => 'automatic',
                'seats' => 8,
                'description' => 'SUV grand format avec une grande capacité de sièges et de remorquage.',
            ],
            [
                'id' => 7,
                'make' => 'Fiat',
                'model' => '500',
                'year' => 2019,
                'license_plate' => 'FF-4007',
                'price_per_day' => 40.00,
                'mileage' => 38000,
                'transmission' => 'manual',
                'seats' => 4,
                'description' => 'Voiture compacte idéale pour la conduite et le stationnement en ville.',
            ],
            [
                'id' => 8,
                'make' => 'Ford',
                'model' => 'Explorer',
                'year' => 2020,
                'license_plate' => 'FF-5008',
                'price_per_day' => 80.00,
                'mileage' => 36000,
                'transmission' => 'automatic',
                'seats' => 7,
                'description' => 'SUV de taille moyenne avec trois rangées et des fonctionnalités de sécurité avancées.',
            ],
            [
                'id' => 9,
                'make' => 'Ford',
                'model' => 'Focus',
                'year' => 2019,
                'license_plate' => 'FF-5009',
                'price_per_day' => 50.00,
                'mileage' => 45000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Voiture compacte fiable avec une bonne consommation de carburant.',
            ],
            [
                'id' => 10,
                'make' => 'Ford',
                'model' => 'Mustang',
                'year' => 2022,
                'license_plate' => 'FF-5010',
                'price_per_day' => 100.00,
                'mileage' => 12000,
                'transmission' => 'automatic',
                'seats' => 4,
                'description' => 'Voiture muscle iconique américaine avec un moteur V8 puissant.',
            ],
            [
                'id' => 11,
                'make' => 'GMC',
                'model' => 'Sierra_1500',
                'year' => 2021,
                'license_plate' => 'GG-6011',
                'price_per_day' => 90.00,
                'mileage' => 25000,
                'transmission' => 'automatic',
                'seats' => 6,
                'description' => 'Pick-up grand format avec une capacité de remorquage impressionnante.',
            ],
            [
                'id' => 12,
                'make' => 'Honda',
                'model' => 'Civic',
                'year' => 2021,
                'license_plate' => 'HH-7012',
                'price_per_day' => 55.00,
                'mileage' => 24000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Berline compacte reconnue pour sa fiabilité et son efficacité énergétique.',
            ],

            [
                'id' => 13,
                'make' => 'Hyundai',
                'model' => 'Sonata',
                'year' => 2020,
                'license_plate' => 'HH-8013',
                'price_per_day' => 60.00,
                'mileage' => 33000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Berline de taille moyenne au design moderne avec des fonctionnalités avancées.',
            ],
            [
                'id' => 14,
                'make' => 'Hyundai',
                'model' => 'Tucson',
                'year' => 2021,
                'license_plate' => 'HH-8014',
                'price_per_day' => 70.00,
                'mileage' => 28000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'SUV compact au design audacieux avec une garantie complète.',
            ],
            [
                'id' => 15,
                'make' => 'Jaguar',
                'model' => 'F-Type',
                'year' => 2022,
                'license_plate' => 'JJ-9015',
                'price_per_day' => 180.00,
                'mileage' => 8000,
                'transmission' => 'automatic',
                'seats' => 2,
                'description' => 'Voiture de sport de luxe au design remarquable et aux performances exaltantes.',
            ],
            [
                'id' => 16,
                'make' => 'Jeep',
                'model' => 'Wrangler',
                'year' => 2021,
                'license_plate' => 'JJ-1016',
                'price_per_day' => 85.00,
                'mileage' => 20000,
                'transmission' => 'manual',
                'seats' => 4,
                'description' => 'SUV robuste tout-terrain avec portes et toit amovibles.',
            ],
            [
                'id' => 17,
                'make' => 'Kia',
                'model' => 'Optima',
                'year' => 2020,
                'license_plate' => 'KK-1117',
                'price_per_day' => 58.00,
                'mileage' => 37000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Berline de taille moyenne au design sportif et au bon rapport qualité-prix.',
            ],
            [
                'id' => 18,
                'make' => 'Land Rover',
                'model' => 'Range Rover Sport',
                'year' => 2022,
                'license_plate' => 'LL-1218',
                'price_per_day' => 150.00,
                'mileage' => 10000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'SUV de luxe alliant élégance et capacités tout-terrain.',
            ],
            [
                'id' => 19,
                'make' => 'Lexus',
                'model' => 'RX 350',
                'year' => 2021,
                'license_plate' => 'LL-1319',
                'price_per_day' => 95.00,
                'mileage' => 18000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'SUV crossover de luxe offrant confort raffiné et fiabilité.',
            ],
            [
                'id' => 20,
                'make' => 'Mazda',
                'model' => 'CX-5',
                'year' => 2020,
                'license_plate' => 'MM-1420',
                'price_per_day' => 65.00,
                'mileage' => 32000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'SUV compact avec un intérieur haut de gamme et une conduite dynamique.',
            ],
            [
                'id' => 21,
                'make' => 'Mercedes-Benz',
                'model' => 'E-Class',
                'year' => 2022,
                'license_plate' => 'MM-1521',
                'price_per_day' => 130.00,
                'mileage' => 14000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Berline de luxe exécutive avec des technologies de pointe.',
            ],
            [
                'id' => 22,
                'make' => 'Mini',
                'model' => 'Cooper',
                'year' => 2020,
                'license_plate' => 'MM-1622',
                'price_per_day' => 50.00,
                'mileage' => 29000,
                'transmission' => 'manual',
                'seats' => 4,
                'description' => 'Voiture compacte au style distinctif et au comportement agile.',
            ],
            [
                'id' => 23,
                'make' => 'Mitsubishi',
                'model' => 'Outlander',
                'year' => 2019,
                'license_plate' => 'MM-1723',
                'price_per_day' => 60.00,
                'mileage' => 41000,
                'transmission' => 'automatic',
                'seats' => 7,
                'description' => 'SUV de taille moyenne avec trois rangées et une garantie longue durée.',
            ],
            [
                'id' => 24,
                'make' => 'Nissan',
                'model' => 'Altima',
                'year' => 2020,
                'license_plate' => 'NN-1824',
                'price_per_day' => 57.00,
                'mileage' => 34000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Berline de taille moyenne avec transmission intégrale intelligente disponible.',
            ],
            [
                'id' => 25,
                'make' => 'Porsche',
                'model' => '911 Carrera',
                'year' => 2022,
                'license_plate' => 'PP-1925',
                'price_per_day' => 250.00,
                'mileage' => 5000,
                'transmission' => 'automatic',
                'seats' => 4,
                'description' => 'Voiture de sport emblématique offrant des performances et une tenue de route légendaires.',
            ],
            [
                'id' => 26,
                'make' => 'Subaru',
                'model' => 'Impreza',
                'year' => 2020,
                'license_plate' => 'SS-2026',
                'price_per_day' => 52.00,
                'mileage' => 39000,
                'transmission' => 'manual',
                'seats' => 5,
                'description' => 'Voiture compacte avec transmission intégrale de série et excellente sécurité.',
            ],
            [
                'id' => 27,
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2021,
                'license_plate' => 'TT-2127',
                'price_per_day' => 85.00,
                'mileage' => 16000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => FuelType::ELECTRIC,
                'description' => 'Berline 100% électrique avec autopilot et mises à jour à distance.',
            ],
            [
                'id' => 28,
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2021,
                'license_plate' => 'TT-2228',
                'price_per_day' => 62.00,
                'mileage' => 26000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'Berline de taille moyenne reconnue pour sa fiabilité et sa valeur de revente.',
            ],
            [
                'id' => 29,
                'make' => 'Volkswagen',
                'model' => 'Golf',
                'year' => 2020,
                'license_plate' => 'VV-2329',
                'price_per_day' => 55.00,
                'mileage' => 31000,
                'transmission' => 'manual',
                'seats' => 5,
                'description' => 'Hatchback compacte avec une ingénierie et une qualité de fabrication européennes.',
            ],
            [
                'id' => 30,
                'make' => 'Volvo',
                'model' => 'XC60',
                'year' => 2021,
                'license_plate' => 'VV-2430',
                'price_per_day' => 88.00,
                'mileage' => 21000,
                'transmission' => 'automatic',
                'seats' => 5,
                'description' => 'SUV compact de luxe doté de technologies de sécurité avancées.',
            ],
        ];


        foreach ($cars as $data) {
            Car::query()->updateOrCreate(
                ['license_plate' => $data['license_plate']],
                $data
            );

            $make = str_replace(' ', '_', $data['make']);
            $modelName = str_replace(' ', '_', $data['model']);

            DB::insert('insert into files (original_name, filename, path, mime_type, size, collection, fileable_id, fileable_type) values (?, ?, ?, ?, ?, ?, ?, ?)', [
                $make . '_' . $modelName,
                $make . '_' . $modelName . '.webp',
                'files/car/' . $data['id'] . '/image/' . $make . '_' . $modelName . '.webp',
                'image/webp',
                100,
                'image',
                $data['id'],
                Car::class
            ]);
        }
    }
}
